### ISSUE TITLE
React & Redux group project: set up your Kanban board

### ISSUE THREAD

**Issue by dev-mamun** [dev-mamun/space-travelers-hub#21]
Hi,
I am continuing as a solo

Here is my [Github Project Link](https://github.com/dev-mamun/space-travelers-hub/projects/1)

**Comment by TuyishimireEric** [comment]
# Status: REQUIRED CHANGES :recycle: 
### hi @dev-mamun 👋 👋 
#### I'm @TuyishimireEric, Your code reviewer,
Good job so far! 🥇 
You still need to work on some issues to go to the next project, but you are almost there!
![](https://camo.githubusercontent.com/6ac905aa3a075ef45de55758c20c6e6efb1dfdbbb0d9fd03d4718d26c5c96cde/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f4a713832345239334a734c775a436169534c2f67697068792e676966)
## Highlight 
✔ All cards are assigned👍 

## Required Changes ♻️

- [ ]  **Good job so far 👏 👏** However, even if you are solo in this group project, It would be better to try to make the complete project for a team with **two** people and it would be better to add all cards except those with the `Team3` prefix on the [template](https://github.com/microverseinc/curriculum-react-redux/projects/1). **The number of cards in the Backlog should be equal to 17.** and I hope you will benefit a lot 😎😎
**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by dev-mamun** [comment]
@TuyishimireEric hi, i remove only the Team3 card, if you could point me to which card is missing it would be better

**Comment by dev-mamun** [comment]
![screenshot-github com-2023 04 21-11_15_01](https://user-images.githubusercontent.com/3351180/233546455-63368a47-d7a8-4305-8cac-2d37140269c3.png)

please check

**Comment by TuyishimireEric** [comment]
Hi @dev-mamun, 👋 
 Kindly we have **24** Cards on the template, 
and the cards with ```Team 3``` prefix are **7**
if you remove them you will remain with **17** cards but currently you have **13** cards

please add the missing **4** cards and submit again for a re-review 🙏

**Comment by dev-mamun** [comment]
@TuyishimireEric yes I see that but how many times I import it only import **20** cards. so when I remove **Team 3** prefix card it became **13** cards

**Comment by TuyishimireEric** [comment]
you may submit again for  a review

**Comment by KayLemba** [comment]
[[# STATUS: APPROVED :green_circle: :clap: 

Hello @dev-mamun      , 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉  Keep up the good work 🥂 

HIGHLIGHTS:

- [x]  Your repo is professional  😎 
- [x] Descriptive P.R 💯 
- [x] linters are passing
- [x] Kanban board setup correctly  🥇 

 










 








Now you can merge this branch and move on :1st_place_medal: 
Happy Coding cheers 🥇 💯 



![well-1](https://user-images.githubusercontent.com/64173189/128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c.gif)

Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._]]
